layout_spectrum: 0.4591473338659853
typography_spectrum: 0.41589055745862424
color:
  brandStrength: 0.41199792665429413
  lightness: 0.2455193866044283
  saturation: 0.7292562460061163
  rhythmicContrast: 0.4098214760888368
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
name: Daily Business
